version: '1.0'

services:
  # container database
  db:
    build: ./database/
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - dockercompose

  # container api
  api:
    depends_on:
      - db
    build: /.api/
    ports:
      - "80:3000"
    restart: always
    networks:
      - dockercompose

networks:
  dockercompose: